---
- hosts: localhost
  become: true
  become_user: julius

  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - user:
        name: julius
        state: present

    - name: Install base packages
      pacman:
        name:
          - git
          - linux
          - ibus
          - xorg-server
          - xorg-xinit
          - xorg-xinput
          - xorg-xrandr
          - base-devel
          - ripgrep
          - adobe-source-han-sans-jp-fonts
          - otf-fira-code
          - sxhkd
          - rofi
          - i3
        state: present
      become: true
      become_user: root

    - name: Install ease of use packages
      pacman:
        name:
          - anki
          - neovim
          - entr
          - emacs
          - fd
          - shellcheck
          - rust
          - rust-racer
          - clang
          - redshift
          - plasma5-applets-redshift-control
          - ruby
          - etckeeper
          - fzf
          - neomutt
          - dunst
          - light
          - fish
          - flatpak
          - picom
          - code
          - docker
          - feh
          - gnome-system-monitor
          - kitty
          - htop
          - lsd
          - dolphin
          - nodejs
          - openssh
          - p7zip
          - pulseaudio
          - pavucontrol-qt
          - python-pillow
          - python-pip
          - ranger
          - ttf-dejavu
          - ttf-liberation
          - libreoffice-fresh
          - unclutter
          - xclip
          - xsel
          - yarn
          - zathura
          - zathura-pdf-mupdf
          - ansible
          - cronie
          - hub
          - make
          - maven
          - neofetch
          - tldr
      become: true
      become_user: root

    - name: install asciidoctor
      gem:
        name: asciidoctor-pdf
        state: present
        pre_release: yes

    - name: install rouge - asciidoc synstax highlighter
      gem:
        name: rouge
        state: present
        pre_release: yes

    - name: check for omf
      stat:
        path: "/home/julius/.local/share/omf"
      register: omf

    - name: clone omf
      git:
        repo: "https://github.com/oh-my-fish/oh-my-fish"
        dest: "/tmp/omf"
        clone: yes
      when: not omf.stat.exists

    - name: Install oh-my-fish
      become: true
      become_user: julius
      command: /tmp/omf/bin/install -y --offline --noninteractive
      when: not omf.stat.exists

    - name: Install yay
      aur:
        name:
          - yay

    - name: Install aur-packages
      aur:
        name:
          - stumpwm-git
          - yadm-git
          - touchpad-toggle
          - vivaldi
          - nvm
          - xbanish
          - xfce-theme-greybird
          - lightscreen

    - name: Install pip-packages
      pip:
        name:
          - neovim
        extra_args: --user

    - name: Clone dotfiles
      command: yadm clone https://github.com/juligreen/Configfiles.git
      become: yes
      become_user: julius
      ignore_errors: yes

    - name: install vim-plug
      command: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      become: yes
      become_user: julius

    - name: install vim plugins
      command: nvim PlugInstall +qall > /dev/null

    - name: install coc extensions
      command: nvim +CocUpdateSync +qall > /dev/null

    - name: Enable multilib repos
      replace:
        path: /etc/pacman.conf
        regexp: '#\[multilib\]\n#.*'
        replace: "[multilib]\nInclude = /etc/pacman.d/mirrorlist"
      become: yes
      become_user: root

    - name: Enable colors
      replace:
        path: /etc/pacman.conf
        regexp: '#Color'
        replace: "Color"
      become: yes
      become_user: root

    - name: install doom-emacs
      command: /home/julius/.emacs.d/bin/doom -y install
      become: yes
      become_user: root

