---
- hosts: localhost
  become: true
  become_user: julius

  tasks:
    - name: pacman packages
      pacman:
        update_cache: yes
        name:
          - steam
          - discord
          - lutris
          - wine-staging
          - nvidia
          - nvidia-utils
          - nvidia-settings
          - lib32-nvidia-utils
          - vulkan-icd-loader
          - lib32-vulkan-icd-loader
          - vagrant
          - ppsspp
          - picard
      become: yes
      become_user: root

    - name: aur packages
      aur:
        name:
          - huestacean
          - steam-fonts
          - xboxdrv
