---
- hosts: localhost
  become: true
  become_user: julius

  tasks:

    - name: pacman packages
      pacman:
        update_cache: yes
        name:
          - steam
      become: yes
      become_user: root

    - name: aur packages
      aur:
        name:
          - discord-canary
          - plex-media-player
          - steam-fonts
