---
- hosts: localhost
  become: true
  become_user: julius
  tasks:

        - name: install doom-emacs
          command: /home/julius/.emacs.d/bin/doom -y install
          become: yes
          become_user: root

