---
- hosts: localhost
  become: true
  become_user: julius
  tasks:

    - name: Enable multilib repos
      replace:
        path: /etc/pacman.conf
        regexp: '#\[multilib\]\n#.*'
        replace: "[multilib]\nInclude = /etc/pacman.d/mirrorlist"
      become: yes
      become_user: root


