---
- hosts: localhost
  become: true
  become_user: julius
  tasks:

    - name: set keymap
      command: localectl --no-convert set-x11-keymap us "" altgr-intl caps:ctrl_modifier 
      become: yes
      become_user: root
