---
- hosts: localhost
  become: true
  become_user: julius
  tasks:

    - name: Install packages
      pacman:
        name:
          - svn
          - maven
          - jdk8-openjdk
          - intellij-idea-community-edition
      become: yes
      become_user: root

    - name: install aur packages
      aur:
        name:
          - slack-desktop

