# directory: /hdd/Audio/Music
# library: /cache/musiclibrary_normal.db
# directory: /hdd/Audio/Vocaloid
# library: /hdd/other_data/musiclibrary.db
# directory: /hdd/Audio/Japanese_Music
# library: /hdd/other_data/japanese_musiclibrary.db
directory: /rclone/Audio/OST
library: /rclone/Audio/libraries/ost_musiclibrary.db
# library: /hdd/other_data/ost_musiclibrary.db
import:
    move: yes
pluginpath:
    - ~/Programs/beets-vocadb/
    - ~/Programs/VGMdb-BeetsPlug/beetsplug
plugins: vocadb edit fetchart convert
edit:
    itemfields: track title artist album albumartist
paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    comp: $albumartist/$album%aunique{}/$track $title
languages: en

convert:
    auto: yes
    dest: /hdd/Audio/temp/
    format: opus
    never_convert_lossy_files: yes
    no_convert: format:mp3
    formats:
        opus:
            command: ffmpeg -i $source -y -vn -acodec libopus -ab 128k $dest
            extension: opus
